apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: kelafat007/lexus:latest
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
